### ISSUE TITLE
[Request] range of ability

### ISSUE THREAD

**Issue by ntsd** [heroespatchnotes/heroes-talents#11]
I think it's very helpful for simulate matchup

**Comment by MGatner** [comment]
Not sure if @stuaroo intentionally didn't include ranges to prevent clutter but if https://github.com/koliva8245/HeroesDataParser includes it I could add them here if they are still wanted

**Comment by stuaroo** [comment]
I'm all for ranges, they just aren't very straightforward in the game data and I have not taken the time to puzzle them out.

**Comment by MGatner** [comment]
koliva8245 at HeroesDataParser says they are a mess and too difficult for the parser. In the interest of moving heroes-talents to a more automated process relying on HeroesDataParser I'm in favor of considering this a "no go" on this request.
