### ISSUE TITLE
Latest Update Missing New Talent Images

### ISSUE THREAD

**Issue by Zemill** [heroespatchnotes/heroes-talents#129]
The latest push to the repo is missing referenced talent images

For example.

Hero: Falstad
Talent:  Frequent Flyer
Icon: storm_ui_icon_falstad_tailwind_a.png

I am waiting to update Heroes Profile from the repo until after those images show up.  

As always, thanks for keeping this repository up-to-date

**Comment by stuaroo** [comment]
Good catch, and I think we'll also need to update Mephisto after the Durance of Hate cast delay was changed back in the hotfix patch
