### ISSUE TITLE
Discuss upcoming changes

### ISSUE THREAD

**Issue by MGatner** [heroespatchnotes/heroes-talents#22]
stuaroo is there a way we could have a more real-time conversation about some changes to the heroes JSON files? I have programmatic game data extraction ready to go and I think it would be easier to sort through some of the nitty-gritty if we could chat. I'm on Gitter.im with the HotsApi chatroom (along with a number of other devs who use heroes-talents), but open to what's best for you.

**Comment by stuaroo** [comment]
Sorry I've been rather unavailable lately, I can try to pop in to the Gitter chat in the near future during normal waking hours (though I'm not very familiar with Gitter to be honest).  If you have any bigger discussion points feel free to list them out here or in other issues, but if it's really just down to a few details then maybe chat would be best.

**Comment by MGatner** [comment]
Generally, a decision on the current repo versus where it deviates from game data. The will temper my pull requests accordingly. 
Hot topics:
* Release date discrepancies
* Spacing differences (double & triple spaces in descriptions)
* Heroes with abnormal / sub abilities: Chen, Kharazim, Alexstrasza, TLV
* Additional identifiers for heroes, talents, abilities
