### ISSUE TITLE
Release date discrepancy

### ISSUE THREAD

**Issue by MGatner** [heroespatchnotes/heroes-talents#23]
Hero JSON (left) differs from extracted game data (right) for the following heroes:

Artanis: 2015-10-20 => 2015-10-27
Azmodan: 2014-10-07 => 2014-10-14
Chen: 2014-09-10 => 2014-09-09
Rehgar: 2014-07-23 => 2014-07-22

Are these dates intentionally altered? Or okay to adjust them to game data values?

**Comment by stuaroo** [comment]
Back in the dark ages before I knew where to look in game files, I had to find a lot of these dates from previous patch notes and community resources (like [gamepedia's list](https://heroesofthestorm.gamepedia.com/List_of_heroes_by_release_date)).  I am of the opinion that those dates from the game data are wrong.  Artanis was released for those who pre-ordered LotV on the 20th, everything I've found shows Azmodan and Anub'arak releasing on the same date (the 7th), Chen and Rehgar dates are both one day earlier than the patches announcing their release (for reasons unknown).

If these need to be changed to make a future update process easier, that's fine I can make adjustments on my end.  But I don't believe those release dates are accurate.

**Comment by MGatner** [comment]
It’s up to you! This is part of the larger discussion mentioned on the other thread, but I’m ready to automate my game data extraction and I can pass those updates on - we just need to get on the same page about what is best. This is your repo and it’s been incredibly helpful to me and many others, so I’m looking to you for how you’d like to maintain it goin forward. If that means only committing new release dates or something, I’m down. 

I’ll look for you on Gitter soon! It’s very easy to use.

**Comment by stuaroo** [comment]
After more thought on this, I think we should update these to match the game data.  Thinking about the future, the goal should be to move towards an accurate reflection of the game files and not necessarily what I think is "correct."  With a different example in mind sometimes we'll have a tooltip that will 100% match what's in-game, but that tooltip is actually bugged and displaying incorrect values.  Yes it's "wrong" but it's as right as we can hope to make it.

**Comment by MGatner** [comment]
Sounds good! Release dates are “fixed” to game data values on updated extraction pull request. They will go master when we’re ready to merge.
