### ISSUE TITLE
Add mana cost per second flag

### ISSUE THREAD

**Issue by stuaroo** [heroespatchnotes/heroes-talents#29]
There are a few abilities (Arthas/Frozen Tempest, Chromie/Swirling Sands, Morales/Healing Beam) that do not have a flat mana/energy cost but rather a cost per second.  The proposed solution is to add a key/value pair to indicate an ability has a cost per second.  Thoughts on naming and data types?

**Comment by MGatner** [comment]
Yes I think that’s an elegant solution. Assuming there will only ever be two mana types - which could need revisiting - of “per cast” and “per second” we could make it a simple Boolean that only appears when relevant. Something like:

manaCost: 1.5
manaPerSecond: true

Alternatively there could be a persistent field that was always “manaType: perCast/perSecond” or something.

**Comment by stuaroo** [comment]
I like Boolean, that's what I was thinking too.  And only appearing when relevant I think would be preferred (because adding a field to every single ability due to 3 cost per second abilities seems silly).  `manaPerSecond: true` looks good to me.

**Comment by MGatner** [comment]
Fixed by https://github.com/heroespatchnotes/heroes-talents/pull/28
