### ISSUE TITLE
Hero field additions

### ISSUE THREAD

**Issue by MGatner** [heroespatchnotes/heroes-talents#30]
There is a line somewhere for the appropriate amount of hero data in this repo, somewhere between “everything available” and “just the name”. I’m not sure if @stuaroo has some guiding principle to pinpoint that line, but two ideas for additions on what is currently here:

* there are five internal hero names used in various places in replay data; devs need access to all of these for full parsing (https://github.com/poma/hotsapi/issues/112)

* hero translations are hard to come by and sometimes are the best way to reverse-lookup a hero ID; these are readily available in the gamedata and I think would make an appropriate addition here

For both of these I would imagine an additional field that was an array of key:value (like “attributeId:FAER” and “itit:Orfea”).

**Comment by stuaroo** [comment]
I've been thinking a little about that lately too, but I'm unsure on any definite lines.  I'd say a good minimum constraint is only things that can be reasonably extracted from game files but I'm not sure where the "too much" line is.  If it helps, my original goal behind the repo was to aid developers who needed ability/talent strings and those working with replay data, so these are all within the scope to me.

Things can get a little tricky with translations though.  As long as we are doing basic info like hero names that should be fine, but once we start talking about adding description fields in different languages I think we should discuss if it's better or worse to do separate hero files by language (i.e. enus, dede, etc.)
