### ISSUE TITLE
Feature request: release patch

### ISSUE THREAD

**Issue by poma** [heroespatchnotes/heroes-talents#40]
As noted in poma/hotsapi#115, it would be cool to have release client version in addition to release date for heroes

**Comment by stuaroo** [comment]
Any preference on full version (i.e. 2.42.0.71134) vs. friendly version (42.0)?

**Comment by poma** [comment]
Full one is better, users can trim it if they want. Also the build number is very useful.

**Comment by MGatner** [comment]
Added to master with https://github.com/heroespatchnotes/heroes-talents/pull/43
