### ISSUE TITLE
Lingering issues from new abilitylinks

### ISSUE THREAD

**Issue by stuaroo** [heroespatchnotes/heroes-talents#46]
#### New abilities added under a "0" key

* ~~Jaina: Improved Ice Block~~
* ~~Kel'Thuzad: Glacial Spike~~

Looks like these were both added as subAbilities on HeroesDataParser, do we just need some handling added to give the label a name?  I think Tychus is another hero with subAbilities that could be referred to.

#### **_stormhero|Z1** listed in abilityLinks and Id 

* Malthael: On a Pale Horse 
* Yrel: Divine Steed

HeroesDataParser uses the abilityLinkIds of `SummonMount` on both of these, which is understandable since neither has a specilized mount, but the _stormhero bit makes it look like a bug whenever I see it.  Do we want to leave as is or attempt to change?

#### talents with abilityIds that no longer map to an ability

* end with a hotkey (ex: HeroName|W)
    * D.Va: Concussive Pulse
    * TLV: Spin to Win, Norse Force, Jump, Nordic Attack Squad
    * ~~Mephisto: Ghastly Armor, Frost Storm, Trickery~~
    * ~~Tracer: Jumper, Bullet Time, Spatial Echo~~
* end with trait (ex: HeroName|Trait)
    * Brightwing: Critical Mist
    * ~~Cassia: Surge of Light~~
    * ~~Deckard: Safety in Numbers~~
    * ~~D.Va: GG, WP; Nanoweave Suit; Suppressing Fire~~
    * Kharazim: Level 1 talents
    * ~~TLV: The Sequel~~
    * ~~Orphea: Invasive Miasma~~
    * ~~Uther: Guardian of Ancient Kings, Redemption, Divine Protection~~

I dug a bit deeper and noticed that these talents do not have abilityLinkId arrays on HeroesDataParser.  Is this an issue with a code default when no array is found maybe?

**Comment by MGatner** [comment]
Very thorough, as always! koliva just posted a new release of HDP - I’ll run that through and see what if this is fixed, then fix what I need to on my end, then pass on to him anything that’s legit bugs. 

Check out the updates: https://github.com/koliva8245/HeroesDataParser/releases/tag/v3.1.0

**Comment by MGatner** [comment]
Jaina & Kel'Thuzad were my fault - didn't notice their abilities were under new subunits that didn't exist before. Fixed with https://github.com/heroespatchnotes/heroes-talents/pull/50

I'm open on _stormhero - anytime there is a reference to it in an abilityId I can provide the hero's name (even if it doesn't have a unique mount ability), or update it to something less "code-like" ("Generic|Mount" or something).

Your list of talents missing abilityIds does seem to be a bug - I will open an issue with @koliva8245

**Comment by stuaroo** [comment]
The original issues list has been resolved over time or marked 'not an issue' on HeroesDataParser, so I'm closing this one out!
