### ISSUE TITLE
Hero Descriptors

### ISSUE THREAD

**Issue by MGatner** [heroespatchnotes/heroes-talents#47]
Koliva added my request for HeroPlaystyleFlags - let me know if you’d like those added here. 

Ref: https://www.reddit.com/r/u_TalesNT/comments/adf47c/comment/edhc0ct

**Comment by stuaroo** [comment]
Sure, those seem like they'd be interesting/useful.  Do they end up as an array of descriptive terms?

**Comment by koliva8245** [comment]
Maiev has none.  Vikings was missing, but I fixed it.
