### ISSUE TITLE
chogall.json references image file that does not exist

### ISSUE THREAD

**Issue by ebshimizu** [heroespatchnotes/heroes-talents#49]
Icon is listed as `chogall.png` which does not exist in `images/heroes`
https://github.com/heroespatchnotes/heroes-talents/blob/6bae8ed9381933084b842bd1e2181a0955d8f4a8/hero/chogall.json#L8

It's a little odd that just Cho is in the `chogall.json` file, seeing as there is an out of date `cho.json` file in the data folder, and a separate `gall.json` file.

**Comment by MGatner** [comment]
We switched to use the internal "shortname" as the basis for the filename. Unfortunately, Cho's official shortname is "chogall" while Gall's is "gall". The Lost Vikings is "lostvikings", which was the other one that changed. Ref: https://github.com/heroespatchnotes/heroes-talents/issues/37
I will clean these up and make sure the icon is there.

**Comment by MGatner** [comment]
Resolved with https://github.com/heroespatchnotes/heroes-talents/pull/50

**Comment by ebshimizu** [comment]
lucky gall getting double credit 😄 
thanks for the quick update!
