### ISSUE TITLE
Yrel missing mana costs, some numeric values (x-post)

### ISSUE THREAD

**Issue by stuaroo** [heroespatchnotes/heroes-talents#58]
I noticed in heroes-talents 44.0 update that Yrel had mana costs removed for Q, W, E and several numeric values are not coming through in the talent/ability descriptions.  Couple examples:

* Seraphim is currently `Activate to become Unstoppable for seconds.`, previously was `Activate to become Unstoppable for 2 seconds.`
* Aldor Peacekeeper is `Enemy Heroes hit by Vindication at maximum charge deal 30% less damage for seconds.`, was `Enemy Heroes hit by Vindication at maximum charge deal 30% less damage for 3 seconds.`

I checked the raw output from HDP and found the same values missing, so I've submitted an [issue on the HeroesDataParser repo](https://github.com/koliva8245/HeroesDataParser/issues/38); cross-posting here to update once the fix is in.

**Comment by stuaroo** [comment]
Welp now I know I don't check issues enough to use them as reminders! 

@MGatner when you have a moment could you get HDP 3.3.1 and re-run the automated process?  I could also attempt a manual update later today if needed, since I believe the only changes will be for Yrel.

**Comment by MGatner** [comment]
Sure! Kicking it off now...

**Comment by stuaroo** [comment]
Sweet, thank you!
