### ISSUE TITLE
Raynor, Nazeebo ability differences

### ISSUE THREAD

**Issue by stuaroo** [heroespatchnotes/heroes-talents#77]
Found a couple more things to fix in the next push @MGatner :

* Raynor's Raider somehow got swapped with `Command Raynor's Raider`, which simply reads: `Order the Banshee to attack an enemy.`
* Nazeebo has two Gargantuan Stomp abilities under `WitchDoctorGargantuan`

**Comment by MGatner** [comment]
Good catches! I have a ticket on Raynor’s Raiders already. I Conan make the switch manually in the meantime but hopefully koliva will have that ready for next patch. I’ll look into Gargantuan today...

**Comment by MGatner** [comment]
Actually I see koliva just released 4.2.3 with a fix for Raynor!
