### ISSUE TITLE
Add a package.json?

### ISSUE THREAD

**Issue by KjellConnelly** [heroespatchnotes/heroes-talents#80]
Not sure if you're interested, but would you add a `package.json` file and add this repo to NPM? Would be very nice to add it to my node app's dependencies. I can create a pull request if you want too, but thought I'd ask first.

**Comment by MGatner** [comment]
Sounds like a great idea! A PR would be great.

**Comment by MGatner** [comment]
@KjellConnelly We have some big updates coming soon - if you're still thinking you could do a PR, any chance you'd be able to get it in soon?

**Comment by KjellConnelly** [comment]
Ya sure, I'll do it tonight :)

**Comment by MGatner** [comment]
@KjellConnelly I made some adjustments to your PR and merged it. One thing I would like you to check.. I moved **index.js** and **test.js** into a subfolder - please make sure I did that correctly so **package.json** and the docs are still accurate.

**Comment by KjellConnelly** [comment]
@MGatner it looks good to me! I'll doubt check later tonight after I get home whether the changes still work, unless you just want to run 

`node dist/test.js`, and see if it still runs. I don't have a computer at work :)

**Comment by MGatner** [comment]
Closed by #86
