### ISSUE TITLE
Deathwing issues

### ISSUE THREAD

**Issue by stuaroo** [heroespatchnotes/heroes-talents#96]
@MGatner Found a couple issues in the Deathwing data:

* Trait description: `Deathwing is fitted with 0##ERROR## Armor Plates which grant 10 Armor`.  Should be 4; I believe I saw a note in one of the recent HDP releases that `##ERROR##` is now used for sections that do not parse correctly
* Hearthstone (B) is listed under abilities

**Comment by MGatner** [comment]
The Plates error was fixed upstream and updated with #97. His Hearthstone is unique (6s channel, no heal) which is why it is showing up, but I guess that probably doesn't merit displaying it since we don't any others - will remove.
